version: '3.8'

services:
  db:
    build:
      context: ./db
    environment:
      POSTGRES_DB: modelosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  php:
    build:
      context: ./php
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
