FROM postgres:latest

ENV POSTGRES_DB=modelosdb
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=123456

# en caso de querer ejecutar un script al iniciar la base de datos
# COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
